AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AudioAdventure-Development
  An audio game developed using Alexa Skill and Watson Assistant

Globals:
  Function:
    Environment:
      Variables:
        STAGE: Development
        CONFIG_FILE: /config_test_endpoints.xml

Resources:
  AlexaHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MainStreamHandler
      Runtime: java11
      CodeUri: ./.aws-sam/build/AlexaHandlerFunction
      MemorySize: 512
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Alexa:
          Type: AlexaSkill
          SkillId: amzn1.ask.skill.70c90c47-8c77-48aa-b57c-2eb6ffdf495c

Outputs:
  AlexaSampleFunctionArn:
    Value: !GetAtt AlexaHandlerFunction.Arn

