AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AudioAdventure
  An audio game developed using Alexa Skill and Watson Assistant

Globals:
  Function:
    Environment:
      Variables:
        STAGE: Production
        CONFIG_FILE: /config.xml

Resources:
  AlexaHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MainStreamHandler
      PackageType: Zip
      Runtime: java11
      CodeUri: ./.aws-sam/build/AlexaHandlerFunction
      MemorySize: 512
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Alexa:
          Type: AlexaSkill
          SkillId: amzn1.ask.skill.702b1548-2887-4379-8bb8-51ac2eb277c9

Outputs:
  AlexaSampleFunctionArn:
    Value: !GetAtt AlexaHandlerFunction.Arn

