version: 2.1
jobs:
  build:
   working_directory: ~/src/main/java
    docker:
      - image:  cimg/openjdk:15.0.0
  steps:
   - checkout
      - run:
          name: The First Step
          command: |
          echo 'Hello World!'
            echo 'This is the delivery pipeline'
